name: Mac OSX GCC

on: [push, pull_request]

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: configure
      run: |
        cmake -B build -G Ninja -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10 -D ZTD_TEXT_TESTS=ON -D ZTD_TEXT_EXAMPLES=ON -D ZTD_TEXT_GENERATE_SINGLE=ON

    - name: build
      run: |
        cmake --build build --config Debug
        cmake --build build --config Release

    - name: test
      run: |
        cd build
        ctest --build-config Debug
        ctest --build-config Release
