name: Windows

on: [push, pull_request]

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@main
      with:
        submodules: recursive
    - uses: seanmiddleditch/gha-setup-ninja@master
    - uses: humbletim/vsdevenv-shell@main
    
    - name: configure
      run: |
        cmake -B build "-DCMAKE_CXX_FLAGS_INIT=/Wv:18" "-DCMAKE_C_FLAGS_INIT=/Wv:18" -D ZTD_TEXT_TESTS=ON -D ZTD_TEXT_EXAMPLES=ON -D ZTD_TEXT_GENERATE_SINGLE=ON -D ZTD_TEXT_BOOST.TEXT=OFF

    - name: build
      run: |
        cmake --build build --config Debug
        cmake --build build --config Release

    - name: test
      run: |
        cd build
        ctest --build-config Debug
        ctest --build-config Release
